# Generated by Django 3.2.18 on 2023-04-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='city',
        ),
        migrations.RemoveField(
            model_name='human',
            name='job',
        ),
        migrations.RemoveField(
            model_name='human',
            name='religion',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Firm',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
